server:
  port: 8021

spring:
  profiles:
    include: API-KEY

#  datasource: # dataSource DB 연결
#    driver-class-name: com.mysql.cj.jdbc.Driver

  devtools:
    livereload:
      enabled: true # 서버 자동 시작

  jpa:
    hibernate:
      show_sql: true
      # TODO(BE) : 1차 스크럼 이후 create가 아닌, 기존정보 유지되는 설정으로 바꾸기
      # create: 기존테이블 삭제 후 다시 생성 (DROP + CREATE)
      # create-drop: create와 같으나 종료시점에 테이블 DROP
      # update: 변경분만 반영(운영DB에서는 사용하면 안됨)
      # validate: 엔티티와 테이블이 정상 매핑되었는지만 확인
      # none: 사용하지 않음(사실상 없는 값이지만 관례상 none이라고 한다.)
      # 개발 초기 단계는 create 또는 update
      # 테스트 서버는 update 또는 validate
      # 스테이징과 운영 서버는 validate 또는 none
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace