server:
  port: 8021

spring:
  profiles:
    include: API-KEY

#  datasource: # dataSource DB 연결
#    driver-class-name: com.mysql.cj.jdbc.Driver

  devtools:
    livereload:
      enabled: true # 서버 자동 시작

mybatis:
  config-location: classpath:mybatis-config.xml
#  #mybatis 페키지 생략 설정
#  type-aliases-package: com.bside.cuokkamap
#  mapper-locations: classpath:mapper/*.xml
