server:
  port: 8021

spring:
  profiles:
    include: API-KEY

#  datasource: # dataSource DB 연결
#    driver-class-name: com.mysql.cj.jdbc.Driver

  devtools:
    livereload:
      enabled: true # 서버 자동 시작

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true