name: Copy Keys

on: [push]

jobs :
  build :
  
    runs-on: ubuntu-latest
    
    steps:
    - name : "copy aws rds keys"
      env:
        AWS_RDS_PASSWORD: ${{ secrets.AWS_RDS_PASSWORD }}
        AWS_RDS_URL: ${{ secrets.AWS_RDS_URL }}
        AWS_RDS_USERNAME: ${{ secrets.AWS_RDS_USERNAME }}
      run:
        echo "AWS_URL => $AWS_RDS_URL"
